version: "2"
services:
    apache:
        build: ./docker/php
        ports: 
            - "8001:80"
        volumes:
            - ./site1:/var/www/html/
            - ./site2:/var/www/workdir/
            - ./site3:/var/www/product/
            - ./site4:/var/www/product2/
            - ./docker/php/sites-enabled/:/etc/apache2/sites-enabled/
        networks:
            - default
volumes:
    persistent: