version: "2"
services:
    apache:
        build: ./docker/php
        ports: 
            - "8001:80"
        volumes:
            - ./site1:/var/www/html/
            - ./site2:/var/www/workdir/
            - ./docker/php/sites-enabled/site1.conf:/etc/apache2/sites-enabled/site1.conf
        networks:
            - default
volumes:
    persistent: